### ISSUE TITLE
[Story]: Hello world! in koala

### ISSUE THREAD

**Issue by adamsonyanik** [ae-lite/koala#2]
# Description
As a developer programming in koala
I want to be able to compile basic koala source code
In order to write and execute simple programs written in koala

# Acceptance Criteria
- the code following should be executable and write "hello world!" in to the stdout.

```koala
class Main

native stdoutPrint(value: String)

main() {
    this.stdoutPrint(value: "hello world!")
}
```

# Subtasks
- [x] implement integration tests
- [x] include and configure antlr for kotlin and gradle
- [x] define the grammar
- [x] extend the ast
- [x] implement an antlr visitor for creating the ast
- [ ] refactor
- [ ] manual testing
